---
pagetitle: "Income Inequality Profiles"
author: "Nikolas Kuschnig"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    css: style.css
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libraries
library(dplyr)
library(plotly)
library(ggplot2)

viris <- rev(c( "#21908CFF", "#20A486FF", "#35B779FF", "#5DC863FF", "#8FD744FF", 
                "#C7E020FF", "#FDE725FF"))
viris_full <- c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")
# generated via:
# viridis::viridis(5, begin = 0)

# Data
countries <- c("Austria" = "AT", "Belgium" = "BE", "Bulgaria" = "BG", 
               "Cyprus" = "CY", "Czech Republic" = "CZ", "Germany" = "DE",
               "Denmark" = "DK", "Estonia" = "EE", "Greece" = "EL",
               "Spain" = "ES", "Finland" = "FI", "France" = "FR", 
               "Croatia" = "HR", "Hungary" = "HU", "Ireland" = "IE",
               "Italy" = "IT", "Lithuania" = "LT", "Latvia" = "LV", 
               "Netherlands" = "NL", "Poland" = "PL", "Portugal" = "PT", 
               "Romania" = "RO", "Sweden" = "SE", "Slovenia" = "SI", 
               "Slovakia" = "SK", "Switzerland" = "CH", "United Kingdom" = "UK")
# These are handpicked, as we do not handle all countries present in the data

neighbours <- readRDS("data/neighbours.rds")
widget <- readRDS("data/widget.rds")
map <- readRDS("data/map.rds")
quantile_stack <- readRDS("data/quantile_stack.rds")
arpr <- readRDS("data/arpr.rds")
gini <- readRDS("data/gini.rds")
inc_mean <- readRDS("data/inc_mean.rds")
inc_med <- readRDS("data/inc_med.rds")
```

```{r, echo=FALSE}
#
# HTML elements
#

# Input for country selection
selector <- selectInput("country", NULL, 
                        choices = countries)
tags$div(
  class = "main_selection",
  tags$h1("Inequality Profile for"),
  selector
)

# Header overview-widget
html_overview <- function(title, number, units, color, href_id) {
  color_hover <- paste0(color, "-h")
  
  out <- tags$div(class = "col-sm-3 plr-5",
  tags$a(href = paste0("#", href_id), 
    class = paste("card widget-card h-100", color_hover),
    tags$div(class = "card-block font-weight-300 py-2 px-2",
    tags$div(class = "media",
    tags$div(class = "d-flex mr-2 align-self-center"),
    tags$div(class = paste("pos-abs width-2 height-2 crnr", color))),
    tags$div(class = "media-body align-self-center",
    tags$div(class = "align-items-center",
    tags$div(class = "widget-title", title),
    tags$div(class = "widget-number-element",
    tags$span(class = "widget-number", number)), 
    tags$div(class = "widget-unit", units)
    ))))
  )
  return(out)
}

output$mean_inc <- renderText(
  format(widget$mean_inc$values[widget$mean_inc$country == input$country], 
         digits = 5, big.mark = ",")
)
output$med_inc <- renderText(
  format(widget$med_inc$values[widget$med_inc$country == input$country], 
         digits = 5, big.mark = ",")
)
output$gini <- renderText(
  format(widget$gini$values[widget$gini$country == input$country] / 100, 
         digits = 2, big.mark = ",")
)
output$qsr80 <- renderText(
  format(widget$qsr$values[widget$qsr$country == input$country], 
         digits = 3, big.mark = ",")
)
output$pov <- renderText(
  format(widget$pov$values[widget$pov$country == input$country], 
         digits = 3, big.mark = ",")
)
output$pov_th <- renderText(
  format(widget$pov_th$values[widget$pov_th$country == input$country], 
         digits = 3, big.mark = ",")
)
output$top10 <- renderText(
  format(widget$top10$values[widget$top10$country == input$country], 
         digits = 3, big.mark = ",")
)

# Create reactive text elements
tags$div(
  class = "row row-tight my-2 mb-2",
  html_overview(
    title = "Mean Income",
    number = textOutput("mean_inc", inline = FALSE),
    units = "(in EUR)",
    color = "bg-yellow",
    href_id = "section1"),
  html_overview(
    title = "Median Income",
    number = textOutput("med_inc", inline = FALSE),
    units = "(in EUR)",
    color = "bg-purple",
    href_id = "section1"),
  html_overview(
    title = "Gini Index",
    number = textOutput("gini", inline = FALSE),
    units = "(0 to 1)",
    color = "bg-darkblue",
    href_id = "section2"),
  html_overview(
    title = "Quantile Share Ratio",
    number = textOutput("qsr80", inline = FALSE),
    units = "(Top vs bottom 20%)",
    color = "bg-yellow",
    href_id = "section2")
)
tags$div(
  class = "row row-tight my-2 mb-2",
    html_overview(
    title = "Top 10% Income Share",
    number = textOutput("top10", inline = FALSE),
    units = "(in percent)",
    color = "bg-yellow",
    href_id = "section2"),
  html_overview(
    title = "Poverty-risk Rate",
    number = textOutput("pov", inline = FALSE),
    units = "(in percent)",
    color = "bg-purple",
    href_id = "section3"),
  html_overview(
    title = "Poverty-risk Threshold",
    number = textOutput("pov_th", inline = FALSE),
    units = "(in EUR)",
    color = "bg-darkblue",
    href_id = "section3")
)
```

```{r echo=FALSE}
#
# Functions and stuff
#

plot_inc <- renderPlotly({
  req(input$country)
  
  inc_mean_self <- inc_mean %>% 
    filter(Country == input$country)
  inc_med_self <- inc_med %>% 
    filter(Country == input$country)
  
  inc_mean <- inc_mean %>% 
    filter(Country %in% neighbours[[input$country]])
  inc_med <- inc_med %>% 
    filter(Country %in% neighbours[[input$country]])
  
  ggplot_inc <- ggplot(inc_mean_self, aes(x = Date)) +
    scale_color_manual(values = viris) +
    geom_line(data = inc_mean, aes(colour = Country, y = Value)) +
    geom_line(data = inc_med, aes(colour = Country, y = Value), linetype = 3) +
    geom_line(data = inc_mean_self, aes(y = Value), colour = viris_full[1]) +
    geom_line(data = inc_med_self, aes(y = Value), colour = viris_full[1], linetype = 3) +
    scale_x_date(expand = c(0, 0), labels = scales::date_format("%Y")) +
    scale_y_continuous(labels = scales::number_format(), expand = c(0, 0)) +
    theme(
      axis.title = element_blank(),
      legend.position = "right",
      legend.justification = "center",
      legend.background = element_blank(),
      legend.title = element_blank(),
      panel.background = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.major.y = element_line(colour = rgb(0.85, 0.85, 0.85), size = 0.2),
      panel.grid.minor = element_blank(),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "lines"))

  ggplotly(ggplot_inc) %>% 
    plotly::config(displaylogo = FALSE, collaborate = FALSE) %>% 
    plotly::layout(legend = list(orientation = "v", yanchor = "center", y = 0.6),
                   yaxis = list(title = "Equivalised net income in EUR", rangemode = "tozero"))
})

plot_map <- renderPlotly({
  map %>% 
    plot_ly(split = ~geo, color = ~values, 
            text = ~paste(geo, "\n", values),
            hoverinfo = "text", hoveron = "fill",
            alpha = 1, showlegend = FALSE) %>% 
    layout(xaxis = list(autorange = FALSE, range = c(-10, 30), title = "(C) EuroGeographics for the administrative boundaries"), 
           yaxis = list(autorange = FALSE, range = c(32, 70))) %>% 
    colorbar(title = "in percent", ticksuffix = "%") %>% 
    plotly::config(displaylogo = FALSE, collaborate = FALSE)
})

plot_quantiles <- renderPlotly({
  quantiles <- quantile_stack %>% 
    filter(geo == input$country) %>% 
    reshape2::dcast(time ~ quantile)
  
  quant_st <- data.frame("time" = quantiles[1], 
                         t(apply(quantiles[-1], 1, function(x) round(x / sum(x), 3) * 100)))
  
  plot_ly(quant_st, x = ~time, y = ~QU1, name = "1st", type = "bar", color = I(viris_full[5]), 
          hoverinfo = "value") %>% 
    add_trace(y = ~QU2, name = "2nd", color = I(viris_full[4])) %>% 
    add_trace(y = ~QU3, name = "3rd", color = I(viris_full[3])) %>% 
    add_trace(y = ~QU4, name = "4th", color = I(viris_full[2])) %>% 
    add_trace(y = ~QU5, name = "5th", color = I(viris_full[1])) %>%  
    plotly::config(displaylogo = FALSE, collaborate = FALSE) %>% 
    plotly::layout(legend = list(orientation = "v", yanchor = "center", y = 0.6),
                   xaxis = list(title = "Year"),
                   yaxis = list(title = "Cumulative share in %"), 
                   barmode = "stack")
})

plot_arpr <- renderPlotly({
  arpr %>% 
    filter(geo == input$country) %>% 
    plot_ly(x = ~time, y = ~values, type = "scatter", mode = "lines", color = I(viris_full[1])) %>%
    plotly::config(displaylogo = FALSE, collaborate = FALSE) %>% 
    layout(xaxis = list(title = "Year"),
           yaxis = list(title = "At-risk-of-poverty rate in %", range = c(0, 30)))
})

plot_gini <- renderPlotly({
  gini %>% 
    filter(geo == input$country) %>% 
    plot_ly(x = ~time, y = ~values, type = "scatter", mode = "lines", color = I(viris_full[1])) %>%
    plotly::config(displaylogo = FALSE, collaborate = FALSE) %>% 
    layout(xaxis = list(title = "Year"),
           yaxis = list(title = "Gini index", range = c(0, 0.5)))
})
```


```{r, echo=FALSE}
#
# Row 1
#
# one full-width card
tags$div(class = "card mb-2", id = "section1",
  tags$div(class = "card-header",
           HTML("Mean and median incomes over time")),
  tags$div(class = "card-body",
           HTML("The equivalised net (or disposable) income (after social transfers) is the total income of households after tax and other deductions, that is available for spending or saving, divided by the number of household members.")),
  tags$div(class = "card-body",
  plot_inc)
)

#
# Row 2
#
# two cards beside each other
tags$div(class = "row mb-2", id = "section2",
  tags$div(class = "col-sm-6",
  tags$div(class = "card", 
  tags$div(class = "card-header",
           HTML("Quintile shares over time")),
  tags$div(class = "card-body",
           HTML("Quantile shares are the shares of total income earned by subgroups of the population, divided by quantiles. E.g. the fifth or top quintile's share is the share of income received by the 20% with the highest income. <br>
The quantile share ratio is the ratio of total income received by the top quintile (the 20% with the highest income) to that received by the bottom quintile.")),
  tags$div(class = "card-body",
           style = "height: 400;",
           plot_quantiles))),
  tags$div(class = "col-sm-6",
  tags$div(class = "card", 
  tags$div(class = "card-header",
           HTML("Gini index over time")),
  tags$div(class = "card-body",
           HTML("The Gini coefficient is a measure of statistical dispersion and is calculated for equivalised disposable income, after social transfers.")),
  tags$div(class = "card-body",
           style = "height: 400;",
           plot_gini)))
)

#
# Row 3
#
# two cards beside each other
tags$div(class = "row mb-2", id = "section3",
  tags$div(class = "col-sm-6",
  tags$div(class = "card", 
  tags$div(class = "card-header",
           HTML("At-risk-of-poverty rate over time")),
  tags$div(class = "card-body",
           HTML("The at-risk-of-poverty rate is the share of people with an equivalised disposable income (after social transfers) below the at-risk-of-poverty threshold.")),
  tags$div(class = "card-body",
           style = "height: 400;",
           plot_arpr))),
  tags$div(class = "col-sm-6",
  tags$div(class = "card", 
  tags$div(class = "card-header",
           HTML("At-risk-of-poverty rates across Europe, 2016")),
  tags$div(class = "card-body",
           HTML("The at-risk-of-poverty threshold is set at 60% of the national median equivalised income (after social transfers).")),
  tags$div(class = "card-body",
           style = "height: 450;",
           plot_map)))
)

# Footer
tags$div(class = "mb-2", id = "footer",
  tags$h4(class = "color-yellow mb-2",
          HTML("<br> Imprint")),
  tags$div(class = "row mt-4 mb-4",
  tags$div(class = "col-sm-12",
  tags$div(class = "footer",
           HTML("
  Contact: shiny@kuschnig.eu <br>
  Sources: Eurostat, Eurostat Statistics Explained, (C) EuroGeographics for the administrative boundaries <br>
  Disclaimer: This document is based on data from Eurostat, EU Statistics on Income and Living Conditions. The responsibility for all conclusions drawn from the data lies entirely with the authors. <br>"))))
)
```
